### PR TITLE
Put cdi-full group on tests that rely on non-empty beans.xml to affect behavior

### PR DESCRIPTION
**Pull request by starksm64**
#334

Signed-off-by: Scott M Stark <starksm64@gmail.com>

### CODE REVIEW

**Comment by starksm64** [comment]
I did not change the package name of these tests to be under the org.jboss.cdi.tck.tests.full.* package. Is this something that should be done?

**Comment by Ladicek** [comment]
In hindsight, I wish we never agreed to move the full-only tests into a `full` package, it's only made a mess. But we should be consistent, so I'd move these tests too :-)

I didn't look at the tests properly, perhaps some of them could/should be copied/rewritten to not use `beans.xml`, so that we don't lose coverage of Lite.

**Comment by manovotn** [comment]
They should be moved under `full` package for consistency.

However, some of these tests seem like they could be just adjusted as they don't really test contents of `beans.xml`.
I'll look into it and provide a PR.

**Comment by manovotn** [comment]
Closing in favor of https://github.com/eclipse-ee4j/cdi-tck/pull/338

**Pull request closed without merging**
