### PR TITLE
Initial prototype of breaking up TCK into a core and web profile set of tests

### PR DESCRIPTION
**Pull request by starksm64**
Work in progress

Signed-off-by: Scott M Stark <starksm64@gmail.com>

### CODE REVIEW

**Comment by manovotn** [comment]
You might want to merge https://github.com/eclipse-ee4j/cdi-tck/pull/224 first

**Comment by starksm64** [comment]
> You might want to merge #224 first

Ok, will do

**Comment by starksm64** [comment]
I have remerged the changes from main and gotten the tests to pass against weld master and wildfly-preview-23.0.2.Final
there are some changes that need to be made to the weld/jboss-tck-runner/pom.xml

**Comment by manovotn** [comment]
> there are some changes that need to be made to the weld/jboss-tck-runner/pom.xml

Ok, please send a PR against Weld.
As soon as there is any CDI API Alpha release, I can swap Weld's default branch to 5.0.0-SNAPSHOT and start accommodating all of these changes. That way we'll have a testable implementation to run all changes against. It should also be fairly easy to adapt WFLY preview to run with even newer CDI/Weld in an automated way (CI) to have the in-container tests covered as well.

BTW the CI build for JDK 8 on this PR is still failing with:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project cdi-tck-api: Fatal error compiling: invalid flag: --release -> [Help 1]

**Comment by starksm64** [comment]
Java SE 11 is going to be the baseline for CDI 4, and it is possible that is will need to run under Java SE 17. We need to update the CI jobs to move beyond SE 8.

**Pull request merged**
