### PR TITLE
Include update for CDITCK-626

### PR DESCRIPTION
**Pull request by starksm64**
Signed-off-by: Scott M Stark <starksm64@gmail.com>

### CODE REVIEW

**Comment by starksm64** [comment]
Ok, I'll look into what happened with my merge and update this PR.

**Comment by starksm64** [comment]
The missing  CDITCK-626 changes have been add to the PR.

**Comment by manovotn** [comment]
@starksm64 looks good, approved. There are conflicts though, you will need to rebase.

**Comment by starksm64** [comment]
I resolved the conflicts with the web editor, so it should be good.

**Pull request merged**
